### ISSUE TITLE
watchdog error

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/TripalTestSuite#114]
this error only appears in `watchdog-show`.

```
 Notice: Trying to get property of non-object in Tests\CVTermTest->tearDown() (line 63 of
                                           /Users/chet/UTK/tripal/sites/all/modules/custom/tripal_curator/tests/CVTermTest.php).

```

my test class doesnt define tearDown.  Does our base class need to define it?

**Comment by almasaeed2010** [comment]
But the class does define tearDown:

https://github.com/statonlab/tripal_curator/blob/master/tests/CVTermTest.php#L60

Also, using `tearDown` (just like `setUp`), requires that you run `parent::tearDown()`.

**Comment by bradfordcondon** [comment]
yeah this looks very much like an implementation error, not a test suite error.
