### ISSUE TITLE
move to tripal so we can pin in there?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/TripalTestSuite#115]
@spficklin discussed adding broadly useful modules to the tripal organization and pinning them.

**Comment by bradfordcondon** [comment]
https://github.com/composer/packagist/issues/47#issuecomment-271962248

Moving the repo organization would mean everyone who has it installed would have to change their composer dependency.

Probably not worth it unfortunately.

**Comment by spficklin** [comment]
Oh, I meant to ask about that.  I think it may be worth it if pinning the repository up beside Tripal would make it more visible and more likely that folks would use it.

**Comment by bradfordcondon** [comment]
@almasaeed2010 you mentioned an alternative solution, mind sharing here?

I think @spficklin 's point that no one is using it yet but us is a really good one.  We just have to change our repos (and @laceysanderson), and core, and we're good.

**Comment by bradfordcondon** [comment]
Also i think having the tool available at tripal/test-suite is just better than at statonlab/test-suite.  You see this path all the time setting it up.  it should make other groups more willing to use it.

**Comment by almasaeed2010** [comment]
I think we can move the repo but keep the package name on Packgist so that no one has to change their dependencies but the repo can live on the tripal organization.

**Comment by almasaeed2010** [comment]
https://github.com/tripal/TripalTestSuite

**Comment by almasaeed2010** [comment]
funny enough, I am not an owner anymore lol

**Comment by laceysanderson** [comment]
I gave the statonlab administrative write access to the repo -is that sufficient @almasaeed2010 or is there something I can do to make it more obvious that this amazing module is available because of you guys? <3

**Comment by almasaeed2010** [comment]
Thanks @laceysanderson 

I think this is perfect. We can add a little collaborators notice on the readme if needed :)

Thanks!
