### ISSUE TITLE
Add collaboration instructions to documentation

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/TripalTestSuite#127]
It'd be nice to have a document that describes the project structure and provides instructions on how to add new features and report and fix bugs.

**Comment by laceysanderson** [comment]
It would also be awesome to have or link to instructions for how to set up a development environment to contribute to TripalTestSuite. (For those of us less familiar with composer and how to contribute to composer projects).

**Comment by almasaeed2010** [comment]
Agreed. That would make the repo more welcoming to new contributors 👍

**Comment by almasaeed2010** [comment]
Finally, we have a guide up. Please see #129.

Thanks!
