### ISSUE TITLE
DBTransaction might be failing

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/TripalTestSuite#136]
Some possibilities:

- Multiple transactions got initiated. Postgresql does not support nested transactions
- DBTransaction is not creating a new transaction with every method. Maybe setUp has been overridden without calling parent::setUp?
- DBTransaction was not correctly tore down at the end of one of the methods causing unintentional nested transactions

**Comment by laceysanderson** [comment]
When running the full tripal test suite on an empty site, I go from 0 content to 54 records (26 organisms, 14 projects and 14 germplasm accessions). All Tripal tests use DBTransaction... and no tests failed.

**Comment by bradfordcondon** [comment]
do you definitely have 0 features?  If so that might be helpful (its not all tests not rolling back, just those in the relationship widget (would account for 14 of each, dont know about the 12 other organisms)

**Comment by laceysanderson** [comment]
Yes, no features! I thought of the relationship widget as well

**Comment by almasaeed2010** [comment]
Confirmed. Running the `sbo__relationship_widgetTest.php` test on its own generates 28 organisms and 0 features although DBTransaction is available.

**Comment by almasaeed2010** [comment]
Ok I think I figured this out. DBTransaction doesn't seem to run when the data comes from  `@dataProvider`

**Comment by almasaeed2010** [comment]
According to this https://stackoverflow.com/a/42161440/1459477, we can't automatically use database transactions when using data providers.

Therefore, the solution means we have to manually run `db_transaction()` at the start of the data provider and roll it back at the end of each test. I'll try it in the `sbo__relationship_widgetTest` class and see if that works.

**Comment by almasaeed2010** [comment]
Issue merged on both core and here 👏 

Thanks all!
