### ISSUE TITLE
provide loader for citrus

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/TripalTestSuite#141]
im going to provide an autoloader for citrus, as thats the "official" tripal core dataset so it will be helpful for matching new user's setups to troubleshoot.

https://tripal.readthedocs.io/en/latest/user_guide/example_genomics.html

**Comment by bradfordcondon** [comment]
ok i wrote a seeder.  @almasaeed2010 do we still want the user seeder as its quite simple?

https://github.com/tripal/TripalTestSuite/blob/citrus_seeder/stubs/CitrusSeeder.php

im also still not sure if it belongs here or if it would be better in tripal core...

**Comment by almasaeed2010** [comment]
The user seeder is just an example and I think examples should be simple and digest-able so I'd vote to keep it or replace it with something related to chado that uses factories to make it even simpler.

**Comment by almasaeed2010** [comment]
Also I don't think we want people to have to go to their tripal installation just to run the seeder. Therefore, I think keeping it here is better.

**Comment by bradfordcondon** [comment]
Re the user example I agree.

I don’t think we’re set up to run seeders in the vendor dir.  it has to get copied over into tests/seeders which is why I was thinking to put it in stubs/why I’m torn on if it should just go in cores test/seeders folder

**Comment by bradfordcondon** [comment]
done.  we now have the blast and interpro annotations as well.
